import { MigrationInterface, QueryRunner } from "typeorm";

export class CriaTabelasIniciais1742967658767 implements MigrationInterface {
    name = 'CriaTabelasIniciais1742967658767'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TYPE "public"."opcoes_campo_nivel_risco_enum" AS ENUM('PADRAO', 'SUCESSO', 'AVISO', 'ERRO')`);
        await queryRunner.query(`CREATE TABLE "opcoes_campo" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "nome" character varying(100) NOT NULL, "alias" character varying NOT NULL, "eh_padrao" boolean NOT NULL DEFAULT false, "nivel_risco" "public"."opcoes_campo_nivel_risco_enum" NOT NULL DEFAULT 'PADRAO', "campo_id" uuid, CONSTRAINT "PK_6f0ce964eb3dc0b8434cb53296f" PRIMARY KEY ("id")); COMMENT ON COLUMN "opcoes_campo"."nome" IS 'Campo tipo slug para usara em referencias fixas'; COMMENT ON COLUMN "opcoes_campo"."alias" IS 'Campo exibido nas labels'; COMMENT ON COLUMN "opcoes_campo"."nivel_risco" IS 'Campo indica um coloração diferente para a opção'`);
        await queryRunner.query(`CREATE TYPE "public"."bloco_imagens_tipo_veiculo_enum" AS ENUM('GENERICO', 'HATCH', 'SEDAN', 'SUV', 'PICAPE', 'MOTO')`);
        await queryRunner.query(`CREATE TABLE "bloco_imagens" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "nome" character varying(75) NOT NULL, "imagem_caminho" character varying NOT NULL, "tipo_veiculo" "public"."bloco_imagens_tipo_veiculo_enum" NOT NULL DEFAULT 'GENERICO', "bloco_id" uuid, CONSTRAINT "PK_f50f5770103fa2ff013300431d1" PRIMARY KEY ("id")); COMMENT ON COLUMN "bloco_imagens"."imagem_caminho" IS 'Somente preenchido quando tipo bloco = imagem'`);
        await queryRunner.query(`CREATE TABLE "campos_coordenadas_imagens" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "coordenada_x_y" character varying(20), "campo_id" uuid, "imagem_id" uuid, CONSTRAINT "PK_1039d31cb9e8c05c0388379c92d" PRIMARY KEY ("id")); COMMENT ON COLUMN "campos_coordenadas_imagens"."coordenada_x_y" IS 'Indicado onde marcar na imagem'`);
        await queryRunner.query(`CREATE TABLE "campos_categorias" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "nome" character varying(100) NOT NULL, CONSTRAINT "PK_0d2e259833417a1a5e4ff2fa6db" PRIMARY KEY ("id")); COMMENT ON COLUMN "campos_categorias"."nome" IS 'nome da categoria'`);
        await queryRunner.query(`CREATE TYPE "public"."campos_tipo_campo_enum" AS ENUM('INPUT', 'INPUT_EMAIL', 'INPUT_MONETARIO', 'INPUT_DATA', 'INPUT_DATA_HORA', 'INPUT_COPIA', 'TEXTO', 'BOLEANO', 'SELECT', 'CHECKBOX', 'SELECT_MULTI', 'RADIO_BUTTON')`);
        await queryRunner.query(`CREATE TABLE "campos" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "nome" character varying(100) NOT NULL, "alias" character varying(100) NOT NULL, "regex_validacao" character varying(100), "mascara" character varying(100), "tipo_campo" "public"."campos_tipo_campo_enum" NOT NULL DEFAULT 'INPUT', "qtd_selecionado" integer NOT NULL DEFAULT '0', "tem_observacao" boolean NOT NULL DEFAULT false, "bloco_id" uuid, "categoria_id" uuid, CONSTRAINT "PK_354272e954a46096a9392ee3c98" PRIMARY KEY ("id")); COMMENT ON COLUMN "campos"."nome" IS 'Campo para usara em referencias especificas'; COMMENT ON COLUMN "campos"."alias" IS 'Campo tipo slug para usara em referencias fixas'; COMMENT ON COLUMN "campos"."regex_validacao" IS 'Validação aplicada no campos tipo input'; COMMENT ON COLUMN "campos"."mascara" IS 'Mascara aplicada nos campos tipo input'; COMMENT ON COLUMN "campos"."qtd_selecionado" IS '0 = campo opcional, 1 = campo obrigatorio, 2=campo multivalorado'; COMMENT ON COLUMN "campos"."tem_observacao" IS 'Caso alem do valor o campo permita observação, tipo item de avaliacao'`);
        await queryRunner.query(`CREATE TYPE "public"."blocos_tipo_bloco_enum" AS ENUM('PADRAO', 'IMAGEM', 'LEITURA', 'UPLOAD')`);
        await queryRunner.query(`CREATE TABLE "blocos" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "nome" character varying(75) NOT NULL, "fontAwesomeIcon" character varying(30), "imagem_caminho" character varying, "tipo_bloco" "public"."blocos_tipo_bloco_enum" NOT NULL DEFAULT 'PADRAO', CONSTRAINT "PK_bfc88d6483d37c14c8f2798af48" PRIMARY KEY ("id")); COMMENT ON COLUMN "blocos"."imagem_caminho" IS 'Somente preenchido quando tipo bloco = imagem'`);
        await queryRunner.query(`CREATE TABLE "estados" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "nome" character varying(70) NOT NULL, "uf" character varying(2) NOT NULL, CONSTRAINT "PK_3d9a9f2658d5086012f27924d30" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "municipios" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "nome" character varying(150) NOT NULL, "estado_id" uuid NOT NULL, CONSTRAINT "PK_10d04b4b4e39ba40240b61e919d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "tipos_endereco" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "descricao" character varying(30) NOT NULL, CONSTRAINT "PK_73f95ea7e39f8657ea38afe9d0b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "enderecos" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "logradouro" character varying(200) NOT NULL, "numero" character varying(15) NOT NULL DEFAULT 'S/N', "complemento" character varying(150) NOT NULL, "cep" character varying(8) NOT NULL, "bairro" character varying(70) NOT NULL, "contato_id" uuid NOT NULL, "municipio_id" uuid NOT NULL, "tipo_endereco_id" uuid NOT NULL, CONSTRAINT "PK_208b05002dcdf7bfbad378dcac1" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "tipos_telefone" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "descricao" character varying(30) NOT NULL, CONSTRAINT "PK_05e2b75fa8af46587a52f6bc7a8" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "telefones" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "numero" character varying(15) NOT NULL, "contato_id" uuid NOT NULL, "tipo_telefone_id" uuid NOT NULL, CONSTRAINT "PK_fa0a7002d74f18ec1a13ca9a4f2" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "emails" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "email" character varying(150) NOT NULL, "eh_principal" boolean NOT NULL, "contato_id" uuid, CONSTRAINT "PK_a54dcebef8d05dca7e839749571" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."clientes_finais_tipo_documento_enum" AS ENUM('PJ', 'PF')`);
        await queryRunner.query(`CREATE TABLE "clientes_finais" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "nomeSocial" character varying(150), "nome_formal" character varying(200) NOT NULL, "documento" character varying(18), "tipo_documento" "public"."clientes_finais_tipo_documento_enum" NOT NULL DEFAULT 'PJ', CONSTRAINT "PK_19ba6772a777609b3e1b412b535" PRIMARY KEY ("id")); COMMENT ON COLUMN "clientes_finais"."nomeSocial" IS 'Apelido para pf e nome fantasia para pj'; COMMENT ON COLUMN "clientes_finais"."nome_formal" IS 'Nome como no RG ou razão social para pj'; COMMENT ON COLUMN "clientes_finais"."documento" IS 'CPF ou CNPJ'`);
        await queryRunner.query(`COMMENT ON TABLE "clientes_finais" IS 'Cliente do nosso cliente, replica a estrutura de pessoa porque não pode ser reaproveitado'`);
        await queryRunner.query(`CREATE TABLE "tipos_contato" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "descricao" character varying(30) NOT NULL, CONSTRAINT "PK_277a817e38e355012339ca971c0" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "contatos" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "tipo_contato_id" uuid NOT NULL, "descricao" character varying(70), "cliente_final_id" uuid, "pessoa_id" uuid, "representante_id" uuid, CONSTRAINT "PK_994cdcb2c56dfb5b66217c854cc" PRIMARY KEY ("id")); COMMENT ON COLUMN "contatos"."cliente_final_id" IS 'Cliente final a quem esse contato pertence'; COMMENT ON COLUMN "contatos"."pessoa_id" IS 'Cliente (pj) a quem esse contato pertence'; COMMENT ON COLUMN "contatos"."representante_id" IS 'Pessoa que representa esse contato, Ex: socio administrador'`);
        await queryRunner.query(`CREATE TYPE "public"."pessoa_tipo_documento_enum" AS ENUM('PJ', 'PF')`);
        await queryRunner.query(`CREATE TABLE "pessoa" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "nomeSocial" character varying(150), "nome_formal" character varying(200) NOT NULL, "documento" character varying(18), "tipo_documento" "public"."pessoa_tipo_documento_enum" NOT NULL DEFAULT 'PJ', CONSTRAINT "UQ_6c2473f6c0b95ee4fa184b3a5fa" UNIQUE ("documento"), CONSTRAINT "PK_bb879ac36994545a5a917a09ba5" PRIMARY KEY ("id")); COMMENT ON COLUMN "pessoa"."nomeSocial" IS 'Apelido para pf e nome fantasia para pj'; COMMENT ON COLUMN "pessoa"."nome_formal" IS 'Nome como no RG ou razão social para pj'; COMMENT ON COLUMN "pessoa"."documento" IS 'CPF ou CNPJ'`);
        await queryRunner.query(`COMMENT ON TABLE "pessoa" IS 'Generalização para clientes que estão em mais de uma posição'`);
        await queryRunner.query(`CREATE TYPE "public"."usuarios_perfil_enum" AS ENUM('SIS_ADMIN', 'ADMINISTRADOR_MATRIZ', 'ADMINISTRADOR_FILIAL', 'USUARIO')`);
        await queryRunner.query(`CREATE TABLE "usuarios" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "nome" character varying(150) NOT NULL, "email" character varying(150) NOT NULL, "perfil" "public"."usuarios_perfil_enum" NOT NULL DEFAULT 'USUARIO', "senha" character varying NOT NULL, "cliente_id" uuid, CONSTRAINT "UQ_446adfc18b35418aac32ae0b7b5" UNIQUE ("email"), CONSTRAINT "PK_d7281c63c176e152e4c531594a8" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."clientes_tipo_cliente_enum" AS ENUM('EMPRESA_UNICA', 'EMPRESA_FRANQUIADORA', 'EMPRESA_FRANQUEADA')`);
        await queryRunner.query(`CREATE TABLE "clientes" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "apelido" character varying(150) NOT NULL, "tipo_cliente" "public"."clientes_tipo_cliente_enum" NOT NULL DEFAULT 'EMPRESA_UNICA', "link_logo" character varying(200), "termo_data_aceite" TIMESTAMP, "termo_usuario_id" character varying, "pessoa_id" uuid NOT NULL, "matriz_id" uuid, CONSTRAINT "PK_d76bf3571d906e4e86470482c08" PRIMARY KEY ("id")); COMMENT ON COLUMN "clientes"."apelido" IS 'nome para exibição em tela, é o msm valor do homônimo em pessoa'`);
        await queryRunner.query(`CREATE TYPE "public"."servicos_tipo_servico_enum" AS ENUM('VISTORIA', 'CONSULTA')`);
        await queryRunner.query(`CREATE TYPE "public"."servicos_integracao_enum" AS ENUM('SEM_CONSULTA', 'CONSULTA_CAUTELAR')`);
        await queryRunner.query(`CREATE TABLE "servicos" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "nome" character varying(150) NOT NULL, "tipo_servico" "public"."servicos_tipo_servico_enum" NOT NULL DEFAULT 'VISTORIA', "custo" numeric(10,2) NOT NULL, "preco" numeric(10,2) NOT NULL, "integracao" "public"."servicos_integracao_enum" NOT NULL DEFAULT 'SEM_CONSULTA', "cliente_id" uuid NOT NULL, CONSTRAINT "PK_91c99670ea2115d2028a48c5e0e" PRIMARY KEY ("id")); COMMENT ON COLUMN "servicos"."custo" IS 'Valor em reais, quanto cobramos do nosso cliente'; COMMENT ON COLUMN "servicos"."preco" IS 'Valor em reais quanto nosso cliente cobra para o cliente final'`);
        await queryRunner.query(`CREATE TABLE "modelos_vistoria" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "nome" character varying(100) NOT NULL, CONSTRAINT "PK_1560c580b319f1ba971e419ea76" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."servicos_externos_status_enum" AS ENUM('PENDENTE', 'CONCLUIDA', 'ERROR')`);
        await queryRunner.query(`CREATE TYPE "public"."servicos_externos_tipo_servico_enum" AS ENUM('SEM_CONSULTA', 'CONSULTA_CAUTELAR', 'BUSCA_CNPJ')`);
        await queryRunner.query(`CREATE TYPE "public"."servicos_externos_fornecedor_enum" AS ENUM('AUTOCRIVO', 'INFO_SIMPLES')`);
        await queryRunner.query(`CREATE TABLE "servicos_externos" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "requisicao" text, "resposta" text, "status" "public"."servicos_externos_status_enum" NOT NULL DEFAULT 'PENDENTE', "tipo_servico" "public"."servicos_externos_tipo_servico_enum" NOT NULL, "fornecedor" "public"."servicos_externos_fornecedor_enum" NOT NULL, CONSTRAINT "PK_44fa32fd9cb62b288fb4ee5a104" PRIMARY KEY ("id")); COMMENT ON COLUMN "servicos_externos"."requisicao" IS 'dados enviados para o servico externo'; COMMENT ON COLUMN "servicos_externos"."resposta" IS 'dados enviados para o servico externo'`);
        await queryRunner.query(`COMMENT ON TABLE "servicos_externos" IS 'Registra os payloads e respostas de todos as integrações realizadas con serviços externos'`);
        await queryRunner.query(`CREATE TYPE "public"."ordem_servico_tipo_dado_consultado_enum" AS ENUM('CHASSI', 'PLACA')`);
        await queryRunner.query(`CREATE TYPE "public"."ordem_servico_status_enum" AS ENUM('AGENDADO', 'AGENDAMENTO_EXPIRADO', 'ANDAMENTO', 'FINALIZADO', 'CANCELADO', 'FRUSTRADO')`);
        await queryRunner.query(`CREATE TYPE "public"."ordem_servico_parecer_vistoria_enum" AS ENUM('APROVADO', 'APROVADO_COM_RESTRICOES', 'NAO_APROVADO', 'SEM_STATUS')`);
        await queryRunner.query(`CREATE TABLE "ordem_servico" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "sequenciador" character varying(50) NOT NULL, "modelo_vistoria_snapshot" jsonb NOT NULL, "tipo_dado_consultado" "public"."ordem_servico_tipo_dado_consultado_enum" NOT NULL DEFAULT 'PLACA', "dado_consultado" character varying(10), "comentario" character varying(200), "custo" numeric(10,2) NOT NULL, "preco" numeric(10,2) NOT NULL, "custo_zerado" boolean NOT NULL DEFAULT false, "status" "public"."ordem_servico_status_enum" NOT NULL DEFAULT 'AGENDADO', "parecer_vistoria" "public"."ordem_servico_parecer_vistoria_enum" NOT NULL DEFAULT 'SEM_STATUS', "cliente_final_id" uuid NOT NULL, "cliente_id" uuid NOT NULL, "modelo_vistoria_id" uuid, "usuario_criador_id" uuid, "usuario_finalizador_id" uuid, "consulta_veicular_id" uuid, CONSTRAINT "REL_1a4dec47fcf2fb6bcdc10a1365" UNIQUE ("consulta_veicular_id"), CONSTRAINT "PK_dccd3809fd45d6946c6a999318c" PRIMARY KEY ("id")); COMMENT ON COLUMN "ordem_servico"."custo" IS 'Valor em reais'; COMMENT ON COLUMN "ordem_servico"."preco" IS 'Valor em reais'`);
        await queryRunner.query(`CREATE TABLE "clientes_clientes_finais" ("cliente_id" uuid NOT NULL, "cliente_final_id" uuid NOT NULL, CONSTRAINT "PK_c484fdcc7f2a21320343bbe070f" PRIMARY KEY ("cliente_id", "cliente_final_id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_5f59a501b6a9b5d59d21061cba" ON "clientes_clientes_finais" ("cliente_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_f0b62c662f831ee1aabbdd9043" ON "clientes_clientes_finais" ("cliente_final_id") `);
        await queryRunner.query(`CREATE TABLE "usuarios_clientes" ("usuario_id" uuid NOT NULL, "cliente_id" uuid NOT NULL, CONSTRAINT "PK_bd2c989e8c4848aff5b7eeb9ef4" PRIMARY KEY ("usuario_id", "cliente_id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_537eddd15bed67dcbbcbe97177" ON "usuarios_clientes" ("usuario_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_47c33cfba10a273673d4aa2afd" ON "usuarios_clientes" ("cliente_id") `);
        await queryRunner.query(`CREATE TABLE "servicos_modelos_vistoria" ("servico_id" uuid NOT NULL, "modelo_vistoria_id" uuid NOT NULL, CONSTRAINT "PK_e745edc2397129e72a4c080981d" PRIMARY KEY ("servico_id", "modelo_vistoria_id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_25ef5d27079674fe1028ca93cf" ON "servicos_modelos_vistoria" ("servico_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_687afc5e7e00d8fe002b318744" ON "servicos_modelos_vistoria" ("modelo_vistoria_id") `);
        await queryRunner.query(`CREATE TABLE "modelos_vistoria_blocos" ("modelo_vistoria_id" uuid NOT NULL, "bloco_id" uuid NOT NULL, CONSTRAINT "PK_1f14fb8b7bc8b985a93da0c1e64" PRIMARY KEY ("modelo_vistoria_id", "bloco_id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_d682bbc9da514fff1e2edf97e5" ON "modelos_vistoria_blocos" ("modelo_vistoria_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_c64f6fc6cac27cfa46cf4c67ff" ON "modelos_vistoria_blocos" ("bloco_id") `);
        await queryRunner.query(`ALTER TABLE "opcoes_campo" ADD CONSTRAINT "FK_d9c5a157875d6ed3828e0679d72" FOREIGN KEY ("campo_id") REFERENCES "campos"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "bloco_imagens" ADD CONSTRAINT "FK_f8aebb4f56137ece03293d8cdbf" FOREIGN KEY ("bloco_id") REFERENCES "blocos"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "campos_coordenadas_imagens" ADD CONSTRAINT "FK_4c58365d0e5d46e5cddee1f03ba" FOREIGN KEY ("campo_id") REFERENCES "campos"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "campos_coordenadas_imagens" ADD CONSTRAINT "FK_d87cb60a6e3398a76d1815bb3fc" FOREIGN KEY ("imagem_id") REFERENCES "bloco_imagens"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "campos" ADD CONSTRAINT "FK_23717120b2d3871a4322c44c9c6" FOREIGN KEY ("bloco_id") REFERENCES "blocos"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "campos" ADD CONSTRAINT "FK_cd89062e72614e4039132d8d7ae" FOREIGN KEY ("categoria_id") REFERENCES "campos_categorias"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "municipios" ADD CONSTRAINT "FK_0314c2f08cd4f988f28a6c2d4f5" FOREIGN KEY ("estado_id") REFERENCES "estados"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "enderecos" ADD CONSTRAINT "FK_6a677540fad67e3abce49ed8a78" FOREIGN KEY ("contato_id") REFERENCES "contatos"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "enderecos" ADD CONSTRAINT "FK_8f662dafd86675aa10a83d89372" FOREIGN KEY ("municipio_id") REFERENCES "municipios"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "enderecos" ADD CONSTRAINT "FK_d3fba5fa9f15e75c4f2cc77962c" FOREIGN KEY ("tipo_endereco_id") REFERENCES "tipos_endereco"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "telefones" ADD CONSTRAINT "FK_9918422e5db82ee8aecc69acb01" FOREIGN KEY ("contato_id") REFERENCES "contatos"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "telefones" ADD CONSTRAINT "FK_9b1d4089c356d179c4f20114070" FOREIGN KEY ("tipo_telefone_id") REFERENCES "tipos_telefone"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "emails" ADD CONSTRAINT "FK_d16e7a6ff7af924958d740727ae" FOREIGN KEY ("contato_id") REFERENCES "contatos"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "contatos" ADD CONSTRAINT "FK_d03ad7448cac571ab70d1ee9f4e" FOREIGN KEY ("tipo_contato_id") REFERENCES "tipos_contato"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "contatos" ADD CONSTRAINT "FK_b9db59800120069e831d097d117" FOREIGN KEY ("cliente_final_id") REFERENCES "clientes_finais"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "contatos" ADD CONSTRAINT "FK_0d66507c0f4e8145c6bca620599" FOREIGN KEY ("pessoa_id") REFERENCES "pessoa"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "contatos" ADD CONSTRAINT "FK_de21ad40c961eedfcf11a660f8d" FOREIGN KEY ("representante_id") REFERENCES "pessoa"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "usuarios" ADD CONSTRAINT "FK_5f4dc9b4cf1f7993658c5c22927" FOREIGN KEY ("cliente_id") REFERENCES "clientes"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "clientes" ADD CONSTRAINT "FK_92f90250bdb09058ada90ef5da7" FOREIGN KEY ("pessoa_id") REFERENCES "pessoa"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "clientes" ADD CONSTRAINT "FK_e388e3e7002b79e95d005141806" FOREIGN KEY ("matriz_id") REFERENCES "clientes"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "servicos" ADD CONSTRAINT "FK_a22c8a56173a760a78b2557c49d" FOREIGN KEY ("cliente_id") REFERENCES "clientes"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ordem_servico" ADD CONSTRAINT "FK_35f8c7664a3e6f1839ee589cdc5" FOREIGN KEY ("cliente_final_id") REFERENCES "clientes_finais"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ordem_servico" ADD CONSTRAINT "FK_1e6fc9a2df0fe9c992559beb41f" FOREIGN KEY ("cliente_id") REFERENCES "clientes"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ordem_servico" ADD CONSTRAINT "FK_4691a76604789cce20768ab8f51" FOREIGN KEY ("modelo_vistoria_id") REFERENCES "modelos_vistoria"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ordem_servico" ADD CONSTRAINT "FK_35f35e36fa018d0c38c8c766097" FOREIGN KEY ("usuario_criador_id") REFERENCES "usuarios"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ordem_servico" ADD CONSTRAINT "FK_6f7b678d4eacfc0ca89ec9d0eec" FOREIGN KEY ("usuario_finalizador_id") REFERENCES "usuarios"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ordem_servico" ADD CONSTRAINT "FK_1a4dec47fcf2fb6bcdc10a13653" FOREIGN KEY ("consulta_veicular_id") REFERENCES "servicos_externos"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "clientes_clientes_finais" ADD CONSTRAINT "FK_5f59a501b6a9b5d59d21061cba1" FOREIGN KEY ("cliente_id") REFERENCES "clientes_finais"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "clientes_clientes_finais" ADD CONSTRAINT "FK_f0b62c662f831ee1aabbdd9043d" FOREIGN KEY ("cliente_final_id") REFERENCES "clientes"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "usuarios_clientes" ADD CONSTRAINT "FK_537eddd15bed67dcbbcbe97177a" FOREIGN KEY ("usuario_id") REFERENCES "usuarios"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "usuarios_clientes" ADD CONSTRAINT "FK_47c33cfba10a273673d4aa2afdc" FOREIGN KEY ("cliente_id") REFERENCES "clientes"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "servicos_modelos_vistoria" ADD CONSTRAINT "FK_25ef5d27079674fe1028ca93cfb" FOREIGN KEY ("servico_id") REFERENCES "servicos"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "servicos_modelos_vistoria" ADD CONSTRAINT "FK_687afc5e7e00d8fe002b3187443" FOREIGN KEY ("modelo_vistoria_id") REFERENCES "modelos_vistoria"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "modelos_vistoria_blocos" ADD CONSTRAINT "FK_d682bbc9da514fff1e2edf97e5e" FOREIGN KEY ("modelo_vistoria_id") REFERENCES "modelos_vistoria"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "modelos_vistoria_blocos" ADD CONSTRAINT "FK_c64f6fc6cac27cfa46cf4c67ff9" FOREIGN KEY ("bloco_id") REFERENCES "blocos"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "modelos_vistoria_blocos" DROP CONSTRAINT "FK_c64f6fc6cac27cfa46cf4c67ff9"`);
        await queryRunner.query(`ALTER TABLE "modelos_vistoria_blocos" DROP CONSTRAINT "FK_d682bbc9da514fff1e2edf97e5e"`);
        await queryRunner.query(`ALTER TABLE "servicos_modelos_vistoria" DROP CONSTRAINT "FK_687afc5e7e00d8fe002b3187443"`);
        await queryRunner.query(`ALTER TABLE "servicos_modelos_vistoria" DROP CONSTRAINT "FK_25ef5d27079674fe1028ca93cfb"`);
        await queryRunner.query(`ALTER TABLE "usuarios_clientes" DROP CONSTRAINT "FK_47c33cfba10a273673d4aa2afdc"`);
        await queryRunner.query(`ALTER TABLE "usuarios_clientes" DROP CONSTRAINT "FK_537eddd15bed67dcbbcbe97177a"`);
        await queryRunner.query(`ALTER TABLE "clientes_clientes_finais" DROP CONSTRAINT "FK_f0b62c662f831ee1aabbdd9043d"`);
        await queryRunner.query(`ALTER TABLE "clientes_clientes_finais" DROP CONSTRAINT "FK_5f59a501b6a9b5d59d21061cba1"`);
        await queryRunner.query(`ALTER TABLE "ordem_servico" DROP CONSTRAINT "FK_1a4dec47fcf2fb6bcdc10a13653"`);
        await queryRunner.query(`ALTER TABLE "ordem_servico" DROP CONSTRAINT "FK_6f7b678d4eacfc0ca89ec9d0eec"`);
        await queryRunner.query(`ALTER TABLE "ordem_servico" DROP CONSTRAINT "FK_35f35e36fa018d0c38c8c766097"`);
        await queryRunner.query(`ALTER TABLE "ordem_servico" DROP CONSTRAINT "FK_4691a76604789cce20768ab8f51"`);
        await queryRunner.query(`ALTER TABLE "ordem_servico" DROP CONSTRAINT "FK_1e6fc9a2df0fe9c992559beb41f"`);
        await queryRunner.query(`ALTER TABLE "ordem_servico" DROP CONSTRAINT "FK_35f8c7664a3e6f1839ee589cdc5"`);
        await queryRunner.query(`ALTER TABLE "servicos" DROP CONSTRAINT "FK_a22c8a56173a760a78b2557c49d"`);
        await queryRunner.query(`ALTER TABLE "clientes" DROP CONSTRAINT "FK_e388e3e7002b79e95d005141806"`);
        await queryRunner.query(`ALTER TABLE "clientes" DROP CONSTRAINT "FK_92f90250bdb09058ada90ef5da7"`);
        await queryRunner.query(`ALTER TABLE "usuarios" DROP CONSTRAINT "FK_5f4dc9b4cf1f7993658c5c22927"`);
        await queryRunner.query(`ALTER TABLE "contatos" DROP CONSTRAINT "FK_de21ad40c961eedfcf11a660f8d"`);
        await queryRunner.query(`ALTER TABLE "contatos" DROP CONSTRAINT "FK_0d66507c0f4e8145c6bca620599"`);
        await queryRunner.query(`ALTER TABLE "contatos" DROP CONSTRAINT "FK_b9db59800120069e831d097d117"`);
        await queryRunner.query(`ALTER TABLE "contatos" DROP CONSTRAINT "FK_d03ad7448cac571ab70d1ee9f4e"`);
        await queryRunner.query(`ALTER TABLE "emails" DROP CONSTRAINT "FK_d16e7a6ff7af924958d740727ae"`);
        await queryRunner.query(`ALTER TABLE "telefones" DROP CONSTRAINT "FK_9b1d4089c356d179c4f20114070"`);
        await queryRunner.query(`ALTER TABLE "telefones" DROP CONSTRAINT "FK_9918422e5db82ee8aecc69acb01"`);
        await queryRunner.query(`ALTER TABLE "enderecos" DROP CONSTRAINT "FK_d3fba5fa9f15e75c4f2cc77962c"`);
        await queryRunner.query(`ALTER TABLE "enderecos" DROP CONSTRAINT "FK_8f662dafd86675aa10a83d89372"`);
        await queryRunner.query(`ALTER TABLE "enderecos" DROP CONSTRAINT "FK_6a677540fad67e3abce49ed8a78"`);
        await queryRunner.query(`ALTER TABLE "municipios" DROP CONSTRAINT "FK_0314c2f08cd4f988f28a6c2d4f5"`);
        await queryRunner.query(`ALTER TABLE "campos" DROP CONSTRAINT "FK_cd89062e72614e4039132d8d7ae"`);
        await queryRunner.query(`ALTER TABLE "campos" DROP CONSTRAINT "FK_23717120b2d3871a4322c44c9c6"`);
        await queryRunner.query(`ALTER TABLE "campos_coordenadas_imagens" DROP CONSTRAINT "FK_d87cb60a6e3398a76d1815bb3fc"`);
        await queryRunner.query(`ALTER TABLE "campos_coordenadas_imagens" DROP CONSTRAINT "FK_4c58365d0e5d46e5cddee1f03ba"`);
        await queryRunner.query(`ALTER TABLE "bloco_imagens" DROP CONSTRAINT "FK_f8aebb4f56137ece03293d8cdbf"`);
        await queryRunner.query(`ALTER TABLE "opcoes_campo" DROP CONSTRAINT "FK_d9c5a157875d6ed3828e0679d72"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c64f6fc6cac27cfa46cf4c67ff"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d682bbc9da514fff1e2edf97e5"`);
        await queryRunner.query(`DROP TABLE "modelos_vistoria_blocos"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_687afc5e7e00d8fe002b318744"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_25ef5d27079674fe1028ca93cf"`);
        await queryRunner.query(`DROP TABLE "servicos_modelos_vistoria"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_47c33cfba10a273673d4aa2afd"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_537eddd15bed67dcbbcbe97177"`);
        await queryRunner.query(`DROP TABLE "usuarios_clientes"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f0b62c662f831ee1aabbdd9043"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5f59a501b6a9b5d59d21061cba"`);
        await queryRunner.query(`DROP TABLE "clientes_clientes_finais"`);
        await queryRunner.query(`DROP TABLE "ordem_servico"`);
        await queryRunner.query(`DROP TYPE "public"."ordem_servico_parecer_vistoria_enum"`);
        await queryRunner.query(`DROP TYPE "public"."ordem_servico_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."ordem_servico_tipo_dado_consultado_enum"`);
        await queryRunner.query(`COMMENT ON TABLE "servicos_externos" IS NULL`);
        await queryRunner.query(`DROP TABLE "servicos_externos"`);
        await queryRunner.query(`DROP TYPE "public"."servicos_externos_fornecedor_enum"`);
        await queryRunner.query(`DROP TYPE "public"."servicos_externos_tipo_servico_enum"`);
        await queryRunner.query(`DROP TYPE "public"."servicos_externos_status_enum"`);
        await queryRunner.query(`DROP TABLE "modelos_vistoria"`);
        await queryRunner.query(`DROP TABLE "servicos"`);
        await queryRunner.query(`DROP TYPE "public"."servicos_integracao_enum"`);
        await queryRunner.query(`DROP TYPE "public"."servicos_tipo_servico_enum"`);
        await queryRunner.query(`DROP TABLE "clientes"`);
        await queryRunner.query(`DROP TYPE "public"."clientes_tipo_cliente_enum"`);
        await queryRunner.query(`DROP TABLE "usuarios"`);
        await queryRunner.query(`DROP TYPE "public"."usuarios_perfil_enum"`);
        await queryRunner.query(`COMMENT ON TABLE "pessoa" IS NULL`);
        await queryRunner.query(`DROP TABLE "pessoa"`);
        await queryRunner.query(`DROP TYPE "public"."pessoa_tipo_documento_enum"`);
        await queryRunner.query(`DROP TABLE "contatos"`);
        await queryRunner.query(`DROP TABLE "tipos_contato"`);
        await queryRunner.query(`COMMENT ON TABLE "clientes_finais" IS NULL`);
        await queryRunner.query(`DROP TABLE "clientes_finais"`);
        await queryRunner.query(`DROP TYPE "public"."clientes_finais_tipo_documento_enum"`);
        await queryRunner.query(`DROP TABLE "emails"`);
        await queryRunner.query(`DROP TABLE "telefones"`);
        await queryRunner.query(`DROP TABLE "tipos_telefone"`);
        await queryRunner.query(`DROP TABLE "enderecos"`);
        await queryRunner.query(`DROP TABLE "tipos_endereco"`);
        await queryRunner.query(`DROP TABLE "municipios"`);
        await queryRunner.query(`DROP TABLE "estados"`);
        await queryRunner.query(`DROP TABLE "blocos"`);
        await queryRunner.query(`DROP TYPE "public"."blocos_tipo_bloco_enum"`);
        await queryRunner.query(`DROP TABLE "campos"`);
        await queryRunner.query(`DROP TYPE "public"."campos_tipo_campo_enum"`);
        await queryRunner.query(`DROP TABLE "campos_categorias"`);
        await queryRunner.query(`DROP TABLE "campos_coordenadas_imagens"`);
        await queryRunner.query(`DROP TABLE "bloco_imagens"`);
        await queryRunner.query(`DROP TYPE "public"."bloco_imagens_tipo_veiculo_enum"`);
        await queryRunner.query(`DROP TABLE "opcoes_campo"`);
        await queryRunner.query(`DROP TYPE "public"."opcoes_campo_nivel_risco_enum"`);
    }

}
