services:
  api:
    build:
      context: .
      dockerfile: docker/api.dockerfile
    container_name: api
    ports:
      - "3001:3000"
      - "9230:9229"
    volumes:
      - ./api:/app
    depends_on:
      - postgres
    networks:
      - postgres_network

  web:
    build:
      context: .
      dockerfile: web/Dockerfile
    container_name: web
    ports:
      - "3000:3000"
      - "9229:9229"
    volumes:
      - ./web:/app
    depends_on:
      - api
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: yourusername
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: yourdatabase
    ports:
      - "5433:5432"
#    volumes:
      # - postgres_data:/var/lib/postgresql/data
    networks:
      - postgres_network
#informar dados do CONTAINER, a conexão é feita no back msm o admin estando na web
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: your-email@example.com
      PGADMIN_DEFAULT_PASSWORD: yourpassword
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - postgres_network

#volumes:
#  postgres_data:

networks:
  postgres_network:
