export enum TipoCampoEnum {
  INPUT = 'INPUT',
  INPUT_EMAIL = 'INPUT_EMAIL',
  INPUT_MONETARIO = 'INPUT_MONETARIO',
  INPUT_DATA = 'INPUT_DATA',
  INPUT_DATA_HORA = 'INPUT_DATA_HORA',
  INPUT_COPIA = 'INPUT_COPIA',//WIP - campo que pode ser copiado de outro campo de outro bloco
  TEXTO = 'TEXTO',
  BOLEANO = 'BOLEANO',
  SELECT = 'SELECT',
  CHECKBOX = 'CHECKBOX',
  SELECT_MULTI = 'SELECT_MULTI',
  RADIO_BUTTON = 'RADIO_BUTTON',
}
