export enum ParecerVistoriaEnum {
  APROVADO = 'APROVADO',//APROVADO
  APROVADO_COM_RESTRICOES = 'APROVADO_COM_RESTRICOES',//APROVADO COM APONTAMENTOS
  NAO_APROVADO = 'NAO_APROVADO',//REPROVADO
  SEM_STATUS = 'SEM_STATUS',//FINALIZAR SEM PARECER
}
