export enum StatusOrdemServicoEnum {
  AGENDADO = 'AGENDADO',
  AGENDAMENTO_EXPIRADO = 'AGENDAMENTO_EXPIRADO',
  ANDAMENTO = 'ANDAMENTO',
  FINALIZADO = 'FINALIZADO',
  CANCELADO = 'CANCELADO',
  FRUSTRADO = 'FRUSTRADO',
}
